#!/usr/bin/env php
<?php

define('IN_CODE', true);
define('LOAD_LEGACY_BOOTSTRAP', false);
require __DIR__ . '/src/bootstrap.php';

use Illuminate\Console\Application;

global $app;
$artisan = new Application($app, $app->make('events.dispatcher'), 'Version 1');
$artisan->setName('webDiplomacy CLI');

// Bind a command
$artisan->resolve(\Diplomacy\Commands\Databases\Seed::class);
$artisan->run();